### PR TITLE
Photoswipe slideshow as alternative to Fotorama

### PR DESCRIPTION
**Pull request by moy**
Hi,

I started the discussion here https://piwigo.org/forum/viewtopic.php?id=32380 but got no reply there.

This draft PR introduces a PhotoSwipe backend as alternative to Fotorama. I initially thought I'd make a separate plugin, but:
- Fotorama has some features (like the thumbnails at the bottom of the screen) that PhotoSwipe lacks. To me the best user experience is Fotorama on desktop and PhotoSwipe on mobile browsers, and having both in the same plugin makes the admin's life simpler (a single administration page for both).
- There's a bunch of code in main.inp.php that I would need to duplicate for a separate plugin, it's better to keep it shared for both backends.

A demo is available here: https://matthieu-moy.fr/piwigo/picture.php?/7/category/1 (I'm using it for development, so it may be broken from time to time).

The PR is still very drafty, the history is dirty, the full-screen icon is broken on light background, there's essentially no configuration for now.

I'd like feedback on the approach. If I do the required clean-up, can this code be merged into Piwigo-Fotorama? Any comments?

An attempt to make a TODO-list:

- [x] Polish the admin page, explain what's PhotoSwipe and Fotorama, have clear sections about what configures what backend
- [x] Clean up history
- [ ] Videos are not supported yet. I won't use this feature, so I've documented this as a limitation for now. The PR is already valuable for people like me who have no videos.
- [x] Re-work the full screen and info icons, they render very badly on white background (white fullscreen image)
- [ ] See whether splitting is needed. Fotorama splits the slideshow by batches of 400 (200 on mobile) images, but this doesn't seem necessary for PhotoSwipe. At least I tested with 460 images and it works smoothly, images are loaded as needed, etc. But more testing is needed on very large collection.
- [ ] I'd like the CSS and JS to be managed with `combine_css` and `combine_script`, but this doesn't work (no idea why for CSS, and probably because the script is a JS module, in both cases I need help).
 
Thanks,

### CODE REVIEW

**Comment by moy** [comment]
I've updated the PR. It's still incomplete in the sense that the plugin doesn't support as many features with PhotoSwipe than with Fotorama, but I believe this is ready for review, and can be integrated. Users who need the Fotorama-only features can still use Fotorama, and people like me who consider zooming on smartphone as more important can start using PhotoSwipe.

From my tests, it seems splitting is not needed, but let me know if I missed something (I didn't test with hugely large galleries yet).

I'm not knowledgeable enough about Smarty, CSS and JS to debug the combine_css / combine_script issue, any help appreciated here. But keeping the code as-is is suboptimal but still works, so I believe this should not be blocking for a merge and can be fixed later.

**Comment by moy** [comment]
Just a ping so that this PR doesn't get forgotten.

@plegall , is there a simple way for you to install this version of the plugin on my gallery https://mmoy.piwigo.com/ ? That would be cool to make a real-life test.

**Comment by plegall** [comment]
OK, I finally took the time to test it. There is a problem with the new settings.

> Warning: Undefined array key "desktop_backend" in /home/plg/git/Piwigo/plugins/Fotorama/main.inc.php on line 89
> Unknown backend '".

This piece of code doesn't add the new settings :

```
    if (empty($conf['Fotorama']))
    {
      $conf['Fotorama'] = serialize($this->default_conf);
      conf_update_param('Fotorama', $conf['Fotorama']);
    }
    else
    {
      $new_conf = is_string($conf['Fotorama']) ? unserialize($conf['Fotorama']) : $conf['Fotorama'];

      $conf['Fotorama'] = serialize($new_conf);
      conf_update_param('Fotorama', $conf['Fotorama']);
    }
```

See https://github.com/Piwigo/Piwigo-Skeleton/blob/master/maintain.class.php to see how it's done with the `option3` (we could also have a `foreach` on all settings, and if not existing, add it based on the `default_conf`

**Comment by moy** [comment]
> OK, I finally took the time to test it. There is a problem with the new settings.

It should be OK now.

I'm mimicking the existing code for consistency, but indeed I'm wondering why the `$default_conf` items are not applied automatically when missing with a basic `foreach` statement.

**Comment by moy** [comment]
The PR has been waiting for a while now. I believe it's ready for a proper review and possibly for merging. Is there anything I can/should do to make that happen?

**Comment by moy** [comment]
Ping, in particular @plegall . I understood from the discussions almost a year ago that the PR was of interest to you, and I got no feedback since then, which is a bit frustrating after spending a few long evenings working on this.

**Comment by LintyDev** [comment]
There's a problem with adding new configuration parameters that we'll sort out in a future commit.

**Pull request merged**
